pipeline:
  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=dev
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_staging_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=staging
    secrets:
      - source: STAGING_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  synch_production_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=production
    secrets:
      - source: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  test:
      image: quay.io/ukhomeofficedigital/cop-node:11
      commands:
        - npm ci
        - npm run linter
        - npm run test:unit
        - npm run coverage
      when:
        event:
        - push
        - pull_request

#  sonar-scanner:
#    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
#    when:
#      status:
#        - failure
#        - success
#      event:
#        - push
#        - pull_request

## Image building
  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t cop-file-upload-service:$${DRONE_COMMIT_SHA} .
    when:
      event: push

#  vulnerability-scan:
#    image: quay.io/ukhomeofficedigital/anchore-submission:latest
#    dockerfile: Dockerfile
#    image_name: cop-file-upload-service:${DRONE_COMMIT_SHA}
#    local_image: true
#    tolerate: low
#    fail_on_detection: false
#    when:
#      branch: master
#      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - source: QUAY_USERNAME
        target: DOCKER_USERNAME
      - source: QUAY_PASSWORD
        target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-file-upload-service
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - AWS_REGION=eu-west-2
    secrets:
      - source: DEV_FILE_UPLOAD_SERVICE_S3_BUCKET_NAME
        target: AWS_BUCKET
      - source: DEV_KUBE_NAMESPACE_PRIVATE_COP
        target: KUBE_NAMESPACE
      - source: DEV_KUBE_SERVER
        target: KUBE_SERVER
      - source: DEV_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: DEV_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: DEV_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: DEV_S3_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY
      - source: DEV_S3_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: PROTOCOL_HTTPS
        target: PROTOCOL
      - source: DEV_WHITELIST
        target: WHITELIST
      - source: DEV_WWW_URL
        target: WWW_URL
      - source: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
        target: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
      - source: FILE_UPLOAD_SERVICE_NAME
        target: FILE_UPLOAD_SERVICE_NAME
      - source: FILE_UPLOAD_SERVICE_PORT
        target: FILE_UPLOAD_SERVICE_PORT
      - source: DEV_FILE_UPLOAD_SERVICE_URL
        target: FILE_UPLOAD_SERVICE_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
      - source: PROTOCOL_HTTPS
        target: KEYCLOAK_PROTOCOL
    commands:
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=10m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_dev_eforms:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - AWS_REGION=eu-west-2
    secrets:
      - source: DEV_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_BUCKET_NAME
        target: AWS_BUCKET
      - source: DEV_KUBE_NAMESPACE_COP_EFORMS
        target: KUBE_NAMESPACE
      - source: DEV_KUBE_SERVER
        target: KUBE_SERVER
      - source: DEV_EFORMS_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: DEV_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: DEV_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: DEV_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY
      - source: DEV_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: PROTOCOL_HTTPS
        target: PROTOCOL
      - source: DEV_WHITELIST
        target: WHITELIST
      - source: DEV_WWW_EFORMS_URL
        target: WWW_URL
      - source: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
        target: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
      - source: FILE_UPLOAD_SERVICE_NAME
        target: FILE_UPLOAD_SERVICE_NAME
      - source: FILE_UPLOAD_SERVICE_PORT
        target: FILE_UPLOAD_SERVICE_PORT
      - source: DEV_FILE_UPLOAD_SERVICE_EFORMS_URL
        target: FILE_UPLOAD_SERVICE_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
      - source: PROTOCOL_HTTPS
        target: KEYCLOAK_PROTOCOL
    commands:
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=10m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - AWS_REGION=eu-west-2
    secrets:
      - source: STAGING_FILE_UPLOAD_SERVICE_S3_BUCKET_NAME
        target: AWS_BUCKET
      - source: STAGING_KUBE_NAMESPACE_PRIVATE_COP
        target: KUBE_NAMESPACE
      - source: STAGING_KUBE_SERVER
        target: KUBE_SERVER
      - source: STAGING_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: STAGING_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: STAGING_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: STAGING_S3_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY
      - source: STAGING_S3_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: PROTOCOL_HTTPS
        target: PROTOCOL
      - source: STAGING_WHITELIST
        target: WHITELIST
      - source: STAGING_WWW_URL
        target: WWW_URL
      - source: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
        target: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
      - source: FILE_UPLOAD_SERVICE_NAME
        target: FILE_UPLOAD_SERVICE_NAME
      - source: FILE_UPLOAD_SERVICE_PORT
        target: FILE_UPLOAD_SERVICE_PORT
      - source: STAGING_FILE_UPLOAD_SERVICE_URL
        target: FILE_UPLOAD_SERVICE_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
      - source: PROTOCOL_HTTPS
        target: KEYCLOAK_PROTOCOL
    commands:
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: staging
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - AWS_REGION=eu-west-2
    secrets:
      - source: PRODUCTION_FILE_UPLOAD_SERVICE_S3_BUCKET_NAME
        target: AWS_BUCKET
      - source: PRODUCTION_KUBE_NAMESPACE_PRIVATE_COP
        target: KUBE_NAMESPACE
      - source: PRODUCTION_KUBE_SERVER
        target: KUBE_SERVER
      - source: PRODUCTION_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: PRODUCTION_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: PRODUCTION_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: PRODUCTION_S3_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY
      - source: PRODUCTION_S3_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: PROTOCOL_HTTPS
        target: PROTOCOL
      - source: PRODUCTION_WHITELIST
        target: WHITELIST
      - source: PRODUCTION_WWW_URL
        target: WWW_URL
      - source: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
        target: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
      - source: FILE_UPLOAD_SERVICE_NAME
        target: FILE_UPLOAD_SERVICE_NAME
      - source: FILE_UPLOAD_SERVICE_PORT
        target: FILE_UPLOAD_SERVICE_PORT
      - source: PRODUCTION_FILE_UPLOAD_SERVICE_URL
        target: FILE_UPLOAD_SERVICE_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
      - source: PROTOCOL_HTTPS
        target: KEYCLOAK_PROTOCOL
    commands:
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment

  deploy_to_production_eforms:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - AWS_REGION=eu-west-2
    secrets:
      - source: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_BUCKET_NAME
        target: AWS_BUCKET
      - source: PRODUCTION_KUBE_NAMESPACE_COP_EFORMS
        target: KUBE_NAMESPACE
      - source: PRODUCTION_KUBE_SERVER
        target: KUBE_SERVER
      - source: PRODUCTION_EFORMS_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: PRODUCTION_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: PRODUCTION_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY
      - source: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: PROTOCOL_HTTPS
        target: PROTOCOL
      - source: PRODUCTION_WHITELIST
        target: WHITELIST
      - source: PRODUCTION_WWW_EFORMS_URL
        target: WWW_URL
      - source: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
        target: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
      - source: FILE_UPLOAD_SERVICE_NAME
        target: FILE_UPLOAD_SERVICE_NAME
      - source: FILE_UPLOAD_SERVICE_PORT
        target: FILE_UPLOAD_SERVICE_PORT
      - source: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_URL
        target: FILE_UPLOAD_SERVICE_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
      - source: PROTOCOL_HTTPS
        target: KEYCLOAK_PROTOCOL
    commands:
      - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=10m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      environment: production
      event: deployment

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
