---
kind: pipeline
type: kubernetes
name: matrix-1

platform:
  os: linux
  arch: amd64

steps:
- name: synch_dev_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: DEV_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: dev
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - secrets

- name: synch_staging_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: STAGING_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: staging
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - secrets

- name: synch_production_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: production
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - secrets

- name: test
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-node:11
  commands:
  - npm ci
  - npm run linter
  - npm run test:unit
  - npm run coverage
  when:
    event:
    - push
    - pull_request

- name: build
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t cop-file-upload-service:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push

- name: vulnerability-scan
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  environment:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: cop-file-upload-service:${DRONE_COMMIT_SHA}
    LOCAL_IMAGE: true
    TOLERATE: low
    WHITELIST_FILE: whitelist
  when:
    branch:
    - master
    event:
    - push

- name: image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-file-upload-service
    tags:
    - ${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  when:
    branch:
    - master
    event:
    - push

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=10m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    AWS_ACCESS_KEY:
      from_secret: DEV_S3_AWS_ACCESS_KEY_ID
    AWS_BUCKET:
      from_secret: DEV_FILE_UPLOAD_SERVICE_S3_BUCKET_NAME
    AWS_REGION: eu-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_S3_AWS_SECRET_ACCESS_KEY
    FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID:
      from_secret: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
    FILE_UPLOAD_SERVICE_LOG_LEVEL:
      from_secret: DEV_FILE_UPLOAD_SERVICE_LOG_LEVEL
    FILE_UPLOAD_SERVICE_NAME:
      from_secret: FILE_UPLOAD_SERVICE_NAME
    FILE_UPLOAD_SERVICE_PORT:
      from_secret: FILE_UPLOAD_SERVICE_PORT
    FILE_UPLOAD_SERVICE_URL:
      from_secret: DEV_FILE_UPLOAD_SERVICE_URL
    FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST:
      from_secret: FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST
    KEYCLOAK_PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    KEYCLOAK_REALM:
      from_secret: DEV_KEYCLOAK_REALM
    KEYCLOAK_URL:
      from_secret: DEV_KEYCLOAK_URL
    KUBE_NAMESPACE:
      from_secret: DEV_KUBE_NAMESPACE_PRIVATE_COP
    KUBE_SERVER:
      from_secret: DEV_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: DEV_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
    PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    WHITELIST:
      from_secret: DEV_WHITELIST
    WWW_URL:
      from_secret: DEV_WWW_URL
  when:
    branch:
    - master
    event:
    - push

- name: deploy_to_dev_eforms
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/internal-network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=10m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    AWS_ACCESS_KEY:
      from_secret: DEV_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_ACCESS_KEY_ID
    AWS_BUCKET:
      from_secret: DEV_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_BUCKET_NAME
    AWS_REGION: eu-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_SECRET_ACCESS_KEY
    FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID:
      from_secret: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
    FILE_UPLOAD_SERVICE_LOG_LEVEL:
      from_secret: DEV_FILE_UPLOAD_SERVICE_LOG_LEVEL
    FILE_UPLOAD_SERVICE_NAME:
      from_secret: FILE_UPLOAD_SERVICE_NAME
    FILE_UPLOAD_SERVICE_PORT:
      from_secret: FILE_UPLOAD_SERVICE_PORT
    FILE_UPLOAD_SERVICE_URL:
      from_secret: DEV_FILE_UPLOAD_SERVICE_EFORMS_URL
    FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST:
      from_secret: FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST
    KEYCLOAK_PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    KEYCLOAK_REALM:
      from_secret: DEV_KEYCLOAK_REALM
    KEYCLOAK_URL:
      from_secret: DEV_KEYCLOAK_URL
    KUBE_NAMESPACE:
      from_secret: DEV_KUBE_NAMESPACE_COP_EFORMS
    KUBE_SERVER:
      from_secret: DEV_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: DEV_EFORMS_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
    PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    WHITELIST:
      from_secret: DEV_WHITELIST
    WWW_URL:
      from_secret: DEV_WWW_EFORMS_URL
  when:
    branch:
    - master
    event:
    - push

- name: deploy_to_staging
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    AWS_ACCESS_KEY:
      from_secret: STAGING_S3_AWS_ACCESS_KEY_ID
    AWS_BUCKET:
      from_secret: STAGING_FILE_UPLOAD_SERVICE_S3_BUCKET_NAME
    AWS_REGION: eu-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: STAGING_S3_AWS_SECRET_ACCESS_KEY
    FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID:
      from_secret: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
    FILE_UPLOAD_SERVICE_LOG_LEVEL:
      from_secret: STAGING_FILE_UPLOAD_SERVICE_LOG_LEVEL
    FILE_UPLOAD_SERVICE_NAME:
      from_secret: FILE_UPLOAD_SERVICE_NAME
    FILE_UPLOAD_SERVICE_PORT:
      from_secret: FILE_UPLOAD_SERVICE_PORT
    FILE_UPLOAD_SERVICE_URL:
      from_secret: STAGING_FILE_UPLOAD_SERVICE_URL
    FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST:
      from_secret: FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST
    KEYCLOAK_PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    KEYCLOAK_REALM:
      from_secret: STAGING_KEYCLOAK_REALM
    KEYCLOAK_URL:
      from_secret: STAGING_KEYCLOAK_URL
    KUBE_NAMESPACE:
      from_secret: STAGING_KUBE_NAMESPACE_PRIVATE_COP
    KUBE_SERVER:
      from_secret: STAGING_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: STAGING_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
    PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    WHITELIST:
      from_secret: STAGING_WHITELIST
    WWW_URL:
      from_secret: STAGING_WWW_URL
  when:
    event:
    - promote
    target:
    - staging

- name: deploy_to_production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/internal-network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=6m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    AWS_ACCESS_KEY:
      from_secret: PRODUCTION_S3_AWS_ACCESS_KEY_ID
    AWS_BUCKET:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_S3_BUCKET_NAME
    AWS_REGION: eu-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: PRODUCTION_S3_AWS_SECRET_ACCESS_KEY
    FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID:
      from_secret: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
    FILE_UPLOAD_SERVICE_LOG_LEVEL:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_LOG_LEVEL
    FILE_UPLOAD_SERVICE_NAME:
      from_secret: FILE_UPLOAD_SERVICE_NAME
    FILE_UPLOAD_SERVICE_PORT:
      from_secret: FILE_UPLOAD_SERVICE_PORT
    FILE_UPLOAD_SERVICE_URL:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_URL
    FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST:
      from_secret: FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST
    KEYCLOAK_PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    KEYCLOAK_REALM:
      from_secret: PRODUCTION_KEYCLOAK_REALM
    KEYCLOAK_URL:
      from_secret: PRODUCTION_KEYCLOAK_URL
    KUBE_NAMESPACE:
      from_secret: PRODUCTION_KUBE_NAMESPACE_PRIVATE_COP
    KUBE_SERVER:
      from_secret: PRODUCTION_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: PRODUCTION_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
    PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    WHITELIST:
      from_secret: PRODUCTION_WHITELIST
    WWW_URL:
      from_secret: PRODUCTION_WWW_URL
  when:
    event:
    - promote
    target:
    - production

- name: deploy_to_production_eforms
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export IMAGE_TAG=$${DRONE_COMMIT_SHA}
  - kd --insecure-skip-tls-verify -f kube/cert.yml
  - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  - kd --insecure-skip-tls-verify -f kube/secret.yml
  - kd --insecure-skip-tls-verify -f kube/service.yml
  - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=10m
  - kd --insecure-skip-tls-verify -f kube/ingress.yml
  environment:
    AWS_ACCESS_KEY:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_ACCESS_KEY_ID
    AWS_BUCKET:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_BUCKET_NAME
    AWS_REGION: eu-west-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_S3_AWS_SECRET_ACCESS_KEY
    FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID:
      from_secret: FILE_UPLOAD_SERVICE_KEYCLOAK_CLIENT_ID
    FILE_UPLOAD_SERVICE_LOG_LEVEL:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_LOG_LEVEL
    FILE_UPLOAD_SERVICE_NAME:
      from_secret: FILE_UPLOAD_SERVICE_NAME
    FILE_UPLOAD_SERVICE_PORT:
      from_secret: FILE_UPLOAD_SERVICE_PORT
    FILE_UPLOAD_SERVICE_URL:
      from_secret: PRODUCTION_FILE_UPLOAD_SERVICE_EFORMS_URL
    FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST:
      from_secret: FILE_UPLOAD_SERVICE_VIRUS_SCAN_HOST
    KEYCLOAK_PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    KEYCLOAK_REALM:
      from_secret: PRODUCTION_KEYCLOAK_REALM
    KEYCLOAK_URL:
      from_secret: PRODUCTION_KEYCLOAK_URL
    KUBE_NAMESPACE:
      from_secret: PRODUCTION_KUBE_NAMESPACE_COP_EFORMS
    KUBE_SERVER:
      from_secret: PRODUCTION_KUBE_SERVER
    KUBE_TOKEN:
      from_secret: PRODUCTION_EFORMS_KUBE_TOKEN
    NGINX_IMAGE:
      from_secret: NGINX_IMAGE
    NGINX_TAG:
      from_secret: NGINX_TAG
    PROTOCOL:
      from_secret: PROTOCOL_HTTPS
    WHITELIST:
      from_secret: PRODUCTION_WHITELIST
    WWW_URL:
      from_secret: PRODUCTION_WWW_EFORMS_URL
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production_eforms

- name: create-change-desc-production
  pull: if-not-exists
  image: docker:git
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - git show --name-only >> $SNOW_DESC_FILE
  environment:
    SNOW_DESC_FILE: /drone/src/change-desc.txt
    SNOW_INT_ID_FILE: /drone/src/internal-id
  when:
    event:
    - promote
    target:
    - production

- name: open-snow-change-production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/snowtify:latest
  environment:
    SNOW_DESC_FILE: /drone/src/change-desc.txt
    SNOW_ENDPOINT:
      from_secret: PRODUCTION_SERVICE_NOW_URL
    SNOW_EXTERNAL_ID: ${DRONE_REPO}:${DRONE_COMMIT_SHA}
    SNOW_INT_ID_FILE: /drone/src/internal-id
    SNOW_PROD_PASS:
      from_secret: PRODUCTION_SERVICE_NOW_PASSWORD
    SNOW_PROD_USER:
      from_secret: PRODUCTION_SERVICE_NOW_USERNAME
  when:
    event:
    - promote
    target:
    - production

- name: complete-snow-change-production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/snowtify:latest
  settings:
    comments: Successful deployment of ${DRONE_REPO}:${DRONE_COMMIT_SHA}
    deployment_outcome: success
  environment:
    SNOW_DESC_FILE: /drone/src/change-desc.txt
    SNOW_ENDPOINT:
      from_secret: PRODUCTION_SERVICE_NOW_URL
    SNOW_INT_ID_FILE: /drone/src/internal-id
    SNOW_PROD_PASS:
      from_secret: PRODUCTION_SERVICE_NOW_PASSWORD
    SNOW_PROD_USER:
      from_secret: PRODUCTION_SERVICE_NOW_USERNAME
  when:
    event:
    - promote
    status:
    - success
    target:
    - production

- name: cancel-snow-change-production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/snowtify:latest
  settings:
    comments: Failed deployment of ${DRONE_REPO}:${DRONE_COMMIT_SHA}
    deployment_outcome: fail
  environment:
    SNOW_DESC_FILE: /drone/src/change-desc.txt
    SNOW_ENDPOINT:
      from_secret: PRODUCTION_SERVICE_NOW_URL
    SNOW_INT_ID_FILE: /drone/src/internal-id
    SNOW_PROD_PASS:
      from_secret: PRODUCTION_SERVICE_NOW_PASSWORD
    SNOW_PROD_USER:
      from_secret: PRODUCTION_SERVICE_NOW_USERNAME
  when:
    event:
    - promote
    status:
    - failure
    target:
    - production

- name: notify
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: cop-deployments
    template: "{{#build.deployTo}}\n  *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*\n  {{build.link}}\n{{else}}\n  *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*\n  {{build.link}}\n{{/build.deployTo}}\n"
    username: Drone Build Watcher
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    branch:
    - master
    event:
    - push
    - promote
    status:
    - success
    - failure

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  commands:
  - /run.sh server

...
