version: '3'

services:
  clamav-api:
    image: quay.io/ukhomeofficedigital/docker-clamav-rest:1.0.0
    environment:
      - CLAMD_HOST=clamav
    ports:
      - 8080:8080
    depends_on:
      - clamav

  clamav:
    image: quay.io/ukhomeofficedigital/clamav:v1.6.1
    ports:
      - 3310:3310

  tesseract:
    image: tesseractshadow/tesseract4re
