---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.FILE_UPLOAD_SERVICE_NAME}}
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
#    ingress.kubernetes.io/whitelist-source-range: {{.WHITELIST}}
    ingress.kubernetes.io/proxy-body-size: "25m"
    stable.k8s.psg.io/kcm.provider: http
spec:
  rules:
  - host: {{.FILE_UPLOAD_SERVICE_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.FILE_UPLOAD_SERVICE_NAME}}
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.FILE_UPLOAD_SERVICE_URL}}
    secretName: {{.FILE_UPLOAD_SERVICE_NAME}}-tls
