---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.FILE_UPLOAD_SERVICE_NAME}}
spec:
  egress:
    - {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-external
      - podSelector:
          matchLabels:
            name: {{.FILE_UPLOAD_SERVICE_NAME}}
      ports:
        - port: 10443
          protocol: TCP
  podSelector:
    matchLabels:
      name: {{.FILE_UPLOAD_SERVICE_NAME}}
  policyTypes:
    - Ingress
    - Egress
