---
apiVersion: v1
kind: Secret
metadata:
  name: {{.FILE_UPLOAD_SERVICE_NAME}}
type: Opaque
data:
  awsAccessKey: "{{.AWS_ACCESS_KEY | b64enc }}"
  awsSecretAccessKey: "{{.AWS_SECRET_ACCESS_KEY | b64enc }}"
