---
apiVersion: v1
kind: Secret
metadata:
  name: {{.FILE_UPLOAD_SERVICE_NAME}}
type: Opaque
data:
  awsSseKmsKeyId: "{{.AWS_SSE_KMS_KEY_ID | b64enc}}"
  awsAccessKey: "{{.AWS_ACCESS_KEY | b64enc }}"
  awsSecretAccessKey: "{{.AWS_SECRET_ACCESS_KEY | b64enc }}"
  awsS3Bucket: "{{.AWS_BUCKET | b64enc }}"
