---
apiVersion: v1
kind: Secret
metadata:
  name: {{.NAME}}
type: Opaque
data:
  sseKmsKeyId: "{{.SSE_KMS_KEY_ID | b64enc}}"
  awsAccessKey: "{{.AWS_ACCESS_KEY | b64enc }}"
  awsSecretAccessKey: "{{.AWS_SECRET_ACCESS_KEY | b64enc }}"
  awsS3Bucket: "{{.AWS_BUCKET | b64enc }}"